function createMarkdownSource({
  id,
  label,
  repo,
  submodulePath,
  sourceKind,
  layoutType,
  pathPatterns,
  canonicalBaseDir = "",
  exclude = [],
  variantDirectories,
  branch = "main",
  cliFamily = "claude",
  directCompatible = true,
  needsCustomParser = false,
  enabled = true,
}) {
  return {
    id,
    label,
    repo,
    branch,
    homepageUrl: `https://github.com/${repo}`,
    sourceType: "git-submodule",
    submodulePath,
    cliFamily,
    sourceKind,
    layoutType,
    fileFormat: "md",
    pathPatterns,
    directCompatible,
    needsRecursiveScan: layoutType === "recursive",
    needsCustomParser,
    enabled,
    discovery: {
      canonical: {
        language: "en",
        baseDir: canonicalBaseDir,
        exclude,
      },
      variants: variantDirectories ?? {
        en: canonicalBaseDir,
      },
    },
  }
}

export const sourceManifest = {
  sources: [
    createMarkdownSource({
      id: "everything-claude-code",
      label: "everything-claude-code",
      repo: "affaan-m/everything-claude-code",
      submodulePath: "vendor/everything-claude-code",
      sourceKind: "agent_markdown_flat",
      layoutType: "flat",
      pathPatterns: ["agents/*.md"],
      canonicalBaseDir: "agents",
      variantDirectories: {
        en: "agents",
        "zh-CN": "docs/zh-CN/agents",
        "zh-TW": "docs/zh-TW/agents",
        tr: "docs/tr/agents",
        "ja-JP": "docs/ja-JP/agents",
        "ko-KR": "docs/ko-KR/agents",
        "pt-BR": "docs/pt-BR/agents",
      },
    }),
    createMarkdownSource({
      id: "0xfurai-claude-code-subagents",
      label: "0xfurai/claude-code-subagents",
      repo: "0xfurai/claude-code-subagents",
      submodulePath: "vendor/0xfurai__claude-code-subagents",
      sourceKind: "agent_markdown_flat",
      layoutType: "flat",
      pathPatterns: ["agents/*.md"],
      canonicalBaseDir: "agents",
    }),
    createMarkdownSource({
      id: "voltagent-awesome-claude-code-subagents",
      label: "VoltAgent/awesome-claude-code-subagents",
      repo: "VoltAgent/awesome-claude-code-subagents",
      submodulePath: "vendor/VoltAgent__awesome-claude-code-subagents",
      sourceKind: "agent_markdown_recursive",
      layoutType: "recursive",
      pathPatterns: ["categories/**/*.md"],
      canonicalBaseDir: "categories",
      exclude: ["categories/**/README.md"],
    }),
    createMarkdownSource({
      id: "iannuttall-claude-agents",
      label: "iannuttall/claude-agents",
      repo: "iannuttall/claude-agents",
      submodulePath: "vendor/iannuttall__claude-agents",
      sourceKind: "agent_markdown_flat",
      layoutType: "flat",
      pathPatterns: ["agents/*.md"],
      canonicalBaseDir: "agents",
    }),
    createMarkdownSource({
      id: "get-shit-done",
      label: "get-shit-done",
      repo: "gsd-build/get-shit-done",
      submodulePath: "vendor/gsd-build__get-shit-done",
      sourceKind: "agent_markdown_flat",
      layoutType: "flat",
      pathPatterns: ["agents/*.md"],
      canonicalBaseDir: "agents",
      variantDirectories: {
        en: "agents",
      },
    }),
  ],
}
